### ISSUE TITLE
Добрый день, очень заинтересовало Ваше решение, но есть одна проблема

### ISSUE THREAD

**Issue by Sergeo312** [uniqby/yii2-ar-translatable#1]
не могу никак выполнить миграцию:
php yii migrate --migrationPath=@uniqby/yii2ArTranslatable/migrations
Вот что пишет:
Migration failed. Directory specified in migrationPath doesn't exist.
Yii2 Изучаю недолго, поэтому прошу строго не судить

**Comment by uniqby** [comment]
Забыл добавить код миграции в коммит. вот структура таблицы, можете вручную пока создать:

```sql
CREATE TABLE language
(
  id int(11) NOT NULL AUTO_INCREMENT,
  url varchar(100)  NOT NULL,
  locale varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  is_default tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

INSERT INTO `language` (`url`, `locale`, `name`, `is_default`) VALUES
('ru',	'ru-RU', 'Русский', 1);
```

**Comment by Sergeo312** [comment]
Благодарю за столь быстрый отклик, буду тестировать.

**Comment by Sergeo312** [comment]
есть второй вопрос:
При попытки сделать вставку:
CREATE TABLE `news_translation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner_id` int(11) unsigned NOT NULL,
  `language_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `short_description` text,
  `full_description` text,
  `meta_title` varchar(255) DEFAULT NULL,
  `meta_keywords` varchar(255) DEFAULT NULL,
  `meta_description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `language_id` (`language_id`),
  KEY `fk_news_translate_news1_idx` (`object_id`),
  CONSTRAINT `fk_NewsTranslate_Language` FOREIGN KEY (`language_id`) REFERENCES `language` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_news_translate_news1` FOREIGN KEY (`owner_id`) REFERENCES `news` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
выдает ошибку :
#1072 - Key column 'object_id' doesn't exist in table
Что я делаю не так.
